# Generated by Django 5.0.2 on 2024-02-28 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='goals',
            fields=[
                ('goal', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('sets', models.CharField(max_length=30)),
                ('reps', models.CharField(max_length=30)),
                ('progover', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='levels',
            fields=[
                ('level', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='muscles',
            fields=[
                ('muscle', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=30)),
                ('paircode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='exercises',
            fields=[
                ('exercise', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('equip', models.CharField(max_length=30)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.levels')),
                ('muscle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.muscles')),
            ],
        ),
    ]
